### ISSUE TITLE
Discord Rebirth - changelog text hard to read

### ISSUE THREAD

**Issue by dashaw92** [0mniscient/Discord-Themes#1]
The red text is hard to see on the dark grey background of the changelog window.
```css
.change-log ul li {
	/*color: #7E1818;*/
        color: #9c9c9c;
}
```
